# Generated by Django 4.2.14 on 2024-07-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_questionnaire_delete_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="color",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="movie",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
